### ISSUE TITLE
/Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/appscript.rb:542:in `_send_command': CommandError (Appscript::CommandError)

### ISSUE THREAD

**Issue by zakiaziz** [scoop/services-to-omnifocus#3]
I have Omnifocus version 2.5.3 (v106.11 r260419)
```
$ ruby services-to-omnifocus.rb
/Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/appscript.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: -1728
		MESSAGE: Can't get reference.
		OFFENDING OBJECT: app("/Applications/OmniFocus.app").default_document.flattened_projects["GitHub"]
		COMMAND: app("/Applications/OmniFocus.app").default_document.flattened_projects["GitHub"].get()
	from /Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/appscript.rb:642:in `method_missing'
	from /Users/zakiaziz/services-to-omnifocus/plugins/github.rb:15:in `<top (required)>'
	from services-to-omnifocus.rb:41:in `require'
	from services-to-omnifocus.rb:41:in `block in <main>'
	from services-to-omnifocus.rb:39:in `each'
	from services-to-omnifocus.rb:39:in `<main>'
```

I'm only using the github script and have moved all over scripts to `/plugins_disabled`. I've put my `GITHUB_TOKEN=XXXXXXXXX` in my `~/.bash_profile`. Did `bundle install` but still receiving this error. Am I missing something?

**Comment by scoop** [comment]
The GitHub script attempts to create tasks in a project called `GitHub` by default, which doesn't seem to exist in your OmniFocus library. If you create that manually (anywhere in the hierarchy) it should run fine.

**Comment by zakiaziz** [comment]
Hi, Thanks for the response. I was able to get it to start working but the script quit unexpectedly in the middle.
```
$ ruby services-to-omnifocus.rb 
Adding: [username/reponame #649]
Adding: [username/reponame #648]
Adding: [username/reponame #646]
Adding: [username/reponame #645]
Adding: [username/reponame #644]
Adding: [username/reponame #643]
Adding: [username/reponame #642]
Adding: [username/reponame #641]
Adding: [username/reponame #639]
Adding: [username/reponame #635]
Adding: [username/reponame #634]
Adding: [username/reponame #633]
Adding: [username/reponame #632]
Adding: [username/reponame #631]
Adding: [username/reponame #630]
Adding: [username/reponame #629]
Adding: [username/reponame #628]
Adding: [username/reponame #627]
Adding: [username/reponame #626]
Adding: [username/reponame #624]
Adding: [username/reponame #622]
Adding: [username/reponame #620]
Adding: [username/reponame #619]
Adding: [username/reponame #617]
Adding: [username/reponame #615]
Adding: [username/reponame #614]
Adding: [username/reponame #610]
Adding: [username/reponame #608]
Adding: [username/reponame #607]
Adding: [username/reponame #606]
/Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/appscript.rb:542:in `_send_command': CommandError (Appscript::CommandError)
		OSERROR: 9
		MESSAGE: Unable to synchronize database with server:

Cannot synchronize.

A synchronization is already in progress.
		COMMAND: app("/Applications/OmniFocus.app").default_document.synchronize()
	from /Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/appscript.rb:642:in `method_missing'
	from services-to-omnifocus.rb:44:in `<main>'
```
Any insights?

**Comment by scoop** [comment]
This just means that a synchronize was already running when the script was triggering it. You can comment line 44 in the main script to disable a manual trigger after the sync itself has completed.

**Comment by zakiaziz** [comment]
That made the errors go away. I hate to keep bothering your but there are a bunch more issues that the script isn't syncing. This is what my terminal outputs now:
```
$ ruby services-to-omnifocus.rb 
Adding: [username/reponame #649]
Adding: [username/reponame #648]
Adding: [username/reponame #646]
Adding: [username/reponame #645]
Adding: [username/reponame #644]
Adding: [username/reponame #643]
Adding: [username/reponame #642]
Adding: [username/reponame #641]
Adding: [username/reponame #639]
Adding: [username/reponame #635]
Adding: [username/reponame #634]
Adding: [username/reponame #633]
Adding: [username/reponame #632]
Adding: [username/reponame #631]
Adding: [username/reponame #630]
Adding: [username/reponame #629]
Adding: [username/reponame #628]
Adding: [username/reponame #627]
Adding: [username/reponame #626]
Adding: [username/reponame #624]
Adding: [username/reponame #622]
Adding: [username/reponame #620]
Adding: [username/reponame #619]
Adding: [username/reponame #617]
Adding: [username/reponame #615]
Adding: [username/reponame #614]
Adding: [username/reponame #610]
Adding: [username/reponame #608]
Adding: [username/reponame #607]
Adding: [username/reponame #606]
```
Does the script only sync the last 30 issues?

**Comment by scoop** [comment]
The GitHub API indeed returns 30 by default and a max or 100 results per query. You can increase the limit by passing `per_page: 100` as an option of line 14 of [github.rb](https://github.com/scoop/services-to-omnifocus/blob/master/plugins/github.rb#L14)

**Comment by zakiaziz** [comment]
If I have more than 100, is there a way to paginate? Forgive me I'm not much of a ruby coder.

**Comment by scoop** [comment]
There are several examples in the documentation of the [Ruby API wrapper](https://github.com/piotrmurach/github/blob/master/README.md#4-pagination) that this script uses on how to do pagination.

**Comment by zakiaziz** [comment]
Thanks, you've been immensely helpful!
